name: Build evilginx2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: cd evilginx2 && go build -o ../evilginx2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: evilginx2
          path: evilginx2
